components:
  parameters:
    productCodePath:
      name: productCode
      in: path
      description: Product code
      required: true
      schema:
        type: string
      example: '123456789'

  schemas:
    ProductInput:
      type: object
      description: Upsert product input
      required:
        - code
        - name
      properties:
        code:
          type: string
          description: Identifier of product
          example: '123456789'
        name:
          type: string
          description: Name of the product
          example: 'apple'

    Product:
      type: object
      description: Product information
      required:
        - code
        - name
      properties:
        code:
          type: string
          description: Identifier of product
          example: '123456789'
        name:
          type: string
          description: Name of the product
          example: 'apple'
