components:

  schemas:
    CreateProductReviewInput:
      type: object
      description: Create product review input
      required:
        - comment
      properties:
        comment:
          type: string
          description: Comment of the review
          example: 'One comment of the product'

    UpdateProductReviewInput:
      type: object
      description: Update product review input
      required:
        - comment
      properties:
        comment:
          type: string
          description: Comment of the review
          example: 'One comment of the product'

    ProductReview:
      type: object
      description: Product review
      required:
        - id
        - comment
      properties:
        id:
          type: string
          example: '123456789:johndoe'
        comment:
          type: string
          description: Comment of the review
          example: 'One comment of the product'
