components:
  parameters:
    productCodePath:
      name: productCode
      in: path
      description: Product code
      required: true
      schema:
        type: string
      example: '123456789'

  schemas:
    ProductStatus:
      type: string
      description: status of the product
      enum:
        - 'PUBLISHED'
        - 'UNPUBLISHED'
      x-enum-varnames:
        - PUBLISHED
        - UNPUBLISHED

    Product:
      type: object
      description: Product information
      required:
        - code
        - status
        - name
      properties:
        code:
          type: string
          description: Identifier of product
          example: '123456789'
        status:
          $ref: '#/components/schemas/ProductStatus'
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'

    ProductInput:
      type: object
      description: Upsert product input
      required:
        - code
        - name
      properties:
        code:
          type: string
          description: Identifier of product
          example: '123456789'
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'

    UpdateProductStatusInput:
      type: object
      description: Update product status input
      required:
        - value
      properties:
        value:
          $ref: '#/components/schemas/ProductStatus'
