components:

  parameters:
    productReviewIdPath:
      name: productReviewId
      in: path
      description: Product Review Id
      required: true
      schema:
        type: string
      example: 'user::asfasfsafasfasfasfsafsafsaf'

  schemas:
    CreateProductReviewInput:
      type: object
      description: Create product review input
      required:
        - comment
      properties:
        comment:
          type: string
          description: Comment of the review
          example: 'One comment of the product'

    ProductReview:
      type: object
      description: Product review
      required:
        - id
        - comment
      properties:
        id:
          type: string
          example: 'adc65c2d-e623-4466-9791-dc76fd6bd1b8:johndoe'
        comment:
          type: string
          description: Comment of the review
          example: 'One comment of the product'
