organization:
  name: "jeferro"

database:
  host: "postgresql"
  port: 5432
  name: "conduktor-console"
  username: "conduktor"
  password: "conduktor"

admin:
  email: admin@admin.com
  password: admin

auth:
  local-users:
    - email: user@user.com
      password: user

monitoring:
  cortex-url: http://conduktor-monitoring:9009/
  alert-manager-url: http://conduktor-monitoring:9010/
  callback-url: http://conduktor-console:8080/monitoring/api/
  notifications-callback-url: http://localhost:8080

clusters:
  - id: local-kafka-cluster
    name: Local Kafka Cluster
    bootstrapServers: "kafka:19092"
    schemaRegistry:
      url: "http://schema-registry:8081"
