metadata:
  application-id: products
  environment: local


spring:
  application:
    name: ${metadata.application-id}

  profiles:
    active: ${metadata.environment}
    include:
      - shared


logging:
  level:
    root: WARN
    com.jeferro: INFO

application:
  products:
    topic: com.jeferro.${metadata.application-id}.products.${metadata.environment}.v1

  product-reviews:
    topic: com.jeferro.${metadata.application-id}.product-reviews.${metadata.environment}.v1
    consumer-group-id: ${metadata.application-id}.product-reviews.${metadata.environment}
    products-topic: ${application.products.topic}
