logging:
  level:
    root: WARN
    com.jeferro: INFO

spring:
  application:
    name: products

  profiles:
    active: local
    include:
      - shared
      - kafka
      - mongo

  threads:
    virtual:
      enabled: true
